CREATE TABLE bondsmen.casesummaries(
  CaseNumber VARCHAR (64) NOT NULL,
  FileDate DATE NOT NULL,
  CaseStatus VARCHAR (64) DEFAULT NULL,
  Offense VARCHAR (64) DEFAULT NULL,
  LastInstrumentFiled VARCHAR (64) DEFAULT NULL,
  Disposition VARCHAR (128) DEFAULT NULL,
  CompletionDate DATE DEFAULT NULL,
  DefendantStatus VARCHAR (64) DEFAULT NULL,
  BondAmount VARCHAR (20) DEFAULT NULL,
  SettingDate DATE DEFAULT NULL,
  DefendantRaceSex VARCHAR (16) DEFAULT NULL,
  DefendantEyes VARCHAR (16) DEFAULT NULL,
  DefendantSkin VARCHAR (16) DEFAULT NULL,
  DefendantDOB DATE DEFAULT NULL,
  DefendantUSCitizen VARCHAR (16) DEFAULT NULL,
  DefendantAddress VARCHAR (512) DEFAULT NULL,
  DefendantMarkings VARCHAR (256) DEFAULT NULL,
  DefendantHeightWeight VARCHAR (32) DEFAULT NULL,
  DefendantHair VARCHAR (16) DEFAULT NULL,
  DefendantBuild VARCHAR (16) DEFAULT NULL,
  DefendantInCustody VARCHAR (16) DEFAULT NULL,
  DefendantPlaceOfBirth VARCHAR (32) DEFAULT NULL,
  CPJCurrentCourt VARCHAR (16) DEFAULT NULL,
  CPJAddress VARCHAR (512) DEFAULT NULL,
  CPJJudgeName VARCHAR (128) DEFAULT NULL,
  CPJCourtType VARCHAR (32) DEFAULT NULL,
  CaseGUID VARCHAR (64) NOT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 20
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.activities(
  CaseId INT (11) NOT NULL,
  `Date` DATE DEFAULT NULL,
  Type VARCHAR (64) NOT NULL,
  Description VARCHAR (512) DEFAULT NULL,
  SnuCfi VARCHAR (32) DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX activity_FK1 USING BTREE (CaseId),
  CONSTRAINT activity_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 46
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.bonds(
  CaseId INT (11) NOT NULL,
  `Date` DATE NOT NULL,
  Type VARCHAR (64) NOT NULL,
  Description VARCHAR (512) DEFAULT NULL,
  SNU VARCHAR (32) DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX bond_FK1 USING BTREE (CaseId),
  CONSTRAINT bond_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 17
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.bookings(
  CaseId INT (11) NOT NULL,
  ArrestDate DATETIME DEFAULT NULL,
  ArrestLocation VARCHAR (64) DEFAULT NULL,
  BookingDate DATETIME DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX booking_FK1 USING BTREE (CaseId),
  CONSTRAINT booking_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 7
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.criminalhistories(
  CaseId INT (11) NOT NULL,
  CaseNumStatus VARCHAR (128) NOT NULL,
  Defendant VARCHAR (128) DEFAULT NULL,
  DateFiledBooked VARCHAR (20) DEFAULT NULL,
  Court VARCHAR (16) DEFAULT NULL,
  DefendantStatus VARCHAR (64) DEFAULT NULL,
  Disposition VARCHAR (128) DEFAULT NULL,
  BondAmount VARCHAR (20) DEFAULT NULL,
  Offense VARCHAR (64) DEFAULT NULL,
  NextSetting DATE DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX criminal_history_FK1 USING BTREE (CaseId),
  CONSTRAINT criminal_history_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 3
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.holds(
  CaseId INT (11) DEFAULT NULL,
  AgencyPlacingHold VARCHAR (64) DEFAULT NULL,
  AgencyName VARCHAR (64) DEFAULT NULL,
  WarrantNumber VARCHAR (64) DEFAULT NULL,
  BondAmount VARCHAR (20) DEFAULT NULL,
  Offense VARCHAR (64) DEFAULT NULL,
  PlacedDate DATE DEFAULT NULL,
  LiftedDate DATE DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX hold_FK1 USING BTREE (CaseId),
  CONSTRAINT hold_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE bondsmen.settings(
  CaseId INT (11) NOT NULL,
  `Date` DATETIME NOT NULL,
  Court VARCHAR (16) DEFAULT NULL,
  PostJdgm VARCHAR (32) DEFAULT NULL,
  DocketType VARCHAR (32) DEFAULT NULL,
  Reason VARCHAR (64) DEFAULT NULL,
  Results VARCHAR (64) DEFAULT NULL,
  Defendant VARCHAR (64) DEFAULT NULL,
  FutureDate DATETIME DEFAULT NULL,
  Comments VARCHAR (128) DEFAULT NULL,
  AttorneyAppearanceIndicator VARCHAR (64) DEFAULT NULL,
  Id INT (11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (Id),
  INDEX setting_FK1 USING BTREE (CaseId),
  CONSTRAINT setting_FK1 FOREIGN KEY (CaseId)
  REFERENCES bondsmen.casesummaries (Id) ON DELETE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 5
CHARACTER SET utf8
COLLATE utf8_general_ci;


